CREATE TABLE IF NOT EXISTS stories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    storyID INTEGER NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    author TEXT NOT NULL,
    storyDate TEXT NOT NULL,
    likes INTEGER NOT NULL,
    dislikes INTEGER
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    admin INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS liked (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   storyID INTEGER NOT NULL,
   userID TEXT NOT NULL,
   title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS disliked (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   storyID INTEGER NOT NULL,
   userID TEXT NOT NULL,
   title TEXT NOT NULL
);
